version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:5.3.1
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
       
  return_api:
    build: 
      context: .
      dockerfile: ./dockerfiles/Dockerfile_returnApi
    volumes:
      - ./microservices/returnApi:/app
    ports:
      - "8000:5000"
    restart: always

  details:
    build: 
      context: .
      dockerfile: ./dockerfiles/Dockerfile_details
    volumes:
      - ./microservices/details:/app
    restart: always

  pdf_generator:
    build: 
      context: .
      dockerfile: ./dockerfiles/Dockerfile_pdfGenerator
    volumes:
      - ./microservices/pdfGenerator:/app
    restart: always

  email_sender:
    build: 
      context: .
      dockerfile: ./dockerfiles/Dockerfile_emailSender
    volumes:
      - ./microservices/emailSender:/app
    restart: always